name: Terraform dev - Artifact 1 Aecorsoft

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Ejecutar terraform apply"
        required: true
        default: false
        type: boolean

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: qas

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: artifact1-aecorsoft

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Create dev.auto.tfvars
        working-directory: artifact1-aecorsoft
        run: |
          cat > dev.auto.tfvars <<EOF
          aws_region             = "${{ secrets.AWS_REGION }}"
          step_function_role_arn = "${{ secrets.STEP_FUNCTION_ROLE_ARN }}"
          EOF

      - name: Terraform init
        working-directory: artifact1-aecorsoft
        run: |
          terraform init \
            -backend-config="key=state/${{ github.event.repository.name }}/terraform.tfstate"

      - name: Terraform plan
        working-directory: artifact1-aecorsoft
        run: |
          terraform plan -out=tfplan \
            -var="github_repository=${{ github.repository }}"

      - name: Terraform apply
        if: ${{ inputs.apply }}
        working-directory: artifact1-aecorsoft
        run: terraform apply -auto-approve tfplan
